package com.divanov.mathwebservice.exception;

<<<<<<< HEAD
import com.divanov.mathwebservice.gen.QuadraticEducationFault;

public class QuadraticEducationException extends Exception {
=======
//import com.divanov.mathwebservice.dto.QuadraticEducationFault;

public class QuadraticEducationException extends Exception {
//    public static final String customFaultCode = "myFaultCode";
//
//    private QuadraticEducationFault faultInfo;
//
//    public QuadraticEducationException(String message) {
//        super(message);
//    }
//
//    public QuadraticEducationException(String message, QuadraticEducationFault faultInfo) {
//        super(message);
//        this.faultInfo = faultInfo;
//    }
//
//    public QuadraticEducationException(String message, Throwable cause, QuadraticEducationFault faultInfo) {
//        super(message, cause);
//        this.faultInfo = faultInfo;
//    }
//
//    public QuadraticEducationFault getFaultInfo() {
//        return faultInfo;
//    }
>>>>>>> e4f4c4c9bf329cce44c475aabd189259a8d3dbc0

}
