
package com.divanov.mathwebservice.generated;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.3
<<<<<<< HEAD:RESTClient/src/main/java/com/divanov/mathwebservice/generated/QuadraticEducationFault_Exception.java
 * 2023-02-27T22:19:30.663+03:00
=======
 * 2023-02-21T20:51:50.456+03:00
>>>>>>> fc3d050d9d5a7fa00c535335ff69abfa8e297c78:RESTClient/src/main/java/com/divanov/mathwebservice/dto/QuadraticEducationFault_Exception.java
 * Generated source version: 3.5.3
 */

@WebFault(name = "quadraticEducationFault", targetNamespace = "http://math.ws.divanov")
public class QuadraticEducationFault_Exception extends Exception {

    private com.divanov.mathwebservice.generated.QuadraticEducationFault faultInfo;

    public QuadraticEducationFault_Exception() {
        super();
    }

    public QuadraticEducationFault_Exception(String message) {
        super(message);
    }

    public QuadraticEducationFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public QuadraticEducationFault_Exception(String message, com.divanov.mathwebservice.generated.QuadraticEducationFault quadraticEducationFault) {
        super(message);
        this.faultInfo = quadraticEducationFault;
    }

    public QuadraticEducationFault_Exception(String message, com.divanov.mathwebservice.generated.QuadraticEducationFault quadraticEducationFault, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = quadraticEducationFault;
    }

    public com.divanov.mathwebservice.generated.QuadraticEducationFault getFaultInfo() {
        return this.faultInfo;
    }
}
